<a href="https://colab.research.google.com/github/Msbohra/Numpy/blob/main/NPS_Numpy_py.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!pip install numpy

In [ ]:
import numpy as np


In [ ]:
a =  [1,2,3,4]

In [ ]:
for i in a:
  print (i**2)


1
4
9
16


In [ ]:
b = [i**2 for i in a]

In [ ]:
b


[1, 4, 9, 16]

In [ ]:
np_a = np.array(a)

In [ ]:
np_a


array([1, 2, 3, 4])

In [ ]:
a

[1, 2, 3, 4]

In [ ]:
type(a)mb


list

In [ ]:
type(np_a)

numpy.ndarray

In [ ]:
np_a.shape

(4,)

numpy is capable of having n dimensionl arrays


In [ ]:
np_a.ndim

1

In [ ]:
l = range(100000)

In [ ]:
%timeit [i**2 for i in l]

40.7 ms ± 9.05 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [ ]:
np_l = np.array(l)

In [ ]:
%timeit np_l**2

64.6 µs ± 7.06 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [ ]:
twod_np = np.array([ [1,2,3], [4,5,6]])

In [ ]:
twod_np

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
np.array([1.2, 3.4, 3],dtype = 'int')

array([1, 3, 3])

ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (2,) + inhomogeneous part.

np.array([[1,2],[3,4,5]])

In [ ]:
a = np.array([1,2,3,4])

In [ ]:
a.astype(float)

array([1., 2., 3., 4.])

to set the type of the data, after the array is creadted


In [ ]:
m1 = np.arange(12)

In [ ]:
m1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [ ]:
l = range(0, 12,2 )

In [ ]:
[i for i in l]

[0, 2, 4, 6, 8, 10]

In [ ]:
m1[0]

0

In [ ]:
m1[-2]

10

In [ ]:
m1[[0,5]]

array([0, 5])

In [ ]:
m1 = np.array([100,200,400,500,700])

In [ ]:
m1[[0,4,2]]

array([100, 700, 400])

In [ ]:
m1[0:5]

array([100, 200, 400, 500, 700])

In [ ]:
m1[:3]

array([100, 200, 400])

In [ ]:
m1[-3:-1]

array([400, 500])

In [ ]:
m1 = np.array([0,0,1,2,3,4,5,6,7,8,9,10])
m1<=6

array([ True,  True,  True,  True,  True,  True,  True,  True, False,
       False, False, False])

In [ ]:
m1[[ True,  True,  True,  True,  True,  True,  True,  True, False,
       False, False, False]]

array([0, 0, 1, 2, 3, 4, 5, 6])

In [ ]:
m1[m1< 4]

array([0, 0, 1, 2, 3])

In [ ]:
m1 [m1%2 ==0]

array([ 0,  0,  2,  4,  6,  8, 10])

In [ ]:
#NPS


In [ ]:
score = np.loadtxt("survey.txt",dtype= "int")

In [ ]:
score

array([ 7, 10,  5, ...,  5,  9, 10])

In [ ]:
type(score)

numpy.ndarray

In [ ]:
score[0]

7

In [ ]:
score.shape

(1167,)

In [ ]:
score.ndim

1

In [ ]:
#NPS = %PROMOTOR - %DETRACTORS

In [ ]:
DETRACTORS = score[score <= 6]

In [ ]:
PROMOTORS = score[score>= 9]

In [ ]:
PROMOTORS.shape

(609,)

In [ ]:
DETRACTORS.shape

(332,)

In [ ]:
num_promotors = len(PROMOTORS)

In [ ]:
num_detractors = len(DETRACTORS)

In [ ]:
total = len(score)

In [ ]:
percentage_promotors = (num_promotors/ total)*100

In [ ]:
percentage_detractors = (num_detractors/ total)*100

In [ ]:
nps = percentage_promotors - percentage_detractors

In [ ]:
nps

23.73607540702657